name: CI test

on:
  push:
    branches: [ GHActionSharing ]
  pull_request:
    branches: [ GHActionSharing ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        build_type: [Release]
        python-version: ["3.9"]
        config-name: ["default"]

    steps: 
      - name: "Test"
        shell: bash
        run: |
          echo ${{ runner.os }}
