name: CI test

on:
  push:
    branches: [ GHActionSharing ]
  pull_request:
    branches: [ GHActionSharing ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] # ubuntu-latest, macOS-latest
        build_type: [Release]
        python-version: ["3.9"]

    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # - name: "Setup OS" 
      #   uses: ./.github/actions/setup-os
      #   with:
      #     python-version: ${{ matrix.python-version }}
      # 
      # - name: "Getting build config"
      #   id: "config"
      #   uses: ./.github/actions/dgtal-config
      #   with:
      #     config-name: "PR"

      - name: "Building and Testing"
        uses: ./.github/actions/cmake
        with:
          build-type: ${{ matrix.build_type }}
          build-config: ${{ steps.config.outputs.cmake-config }}
          test: true