name: CI (linux/macOS/windows), master

on:
  push:
    branches: [ MacDebug ]
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macOS-latest]
        BUILD_TYPE: [Debug]

    steps:
     - uses: actions/checkout@v3
       with:
          fetch-depth: 10

     - name: Install macOS deps
       run: brew install boost ninja gmp libomp cgal

     - name: Create Build Environment
       run: cmake -E make_directory ${{runner.workspace}}/build

     - name: Configure CMake (macOS)
       shell: bash
       working-directory: ${{runner.workspace}}/build
       run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DDGTAL_BUILD_EXAMPLES=true -DDGTAL_BUILD_TESTS=true -DDGTAL_RANDOMIZED_TESTING_THRESHOLD=100 -DDGTAL_WITH_GMP=true -DDGTAL_BUILD_POLYSCOPE_EXAMPLES=true -DDGTAL_WITH_CGAL=true -DDGTAL_WITH_LIBIGL=true

     - name: Build
       working-directory: ${{runner.workspace}}/build
       shell: bash
       # Execute the build.  You can specify a specific target with "--target <NAME>"
       run: cmake --build . --config ${{ matrix.BUILD_TYPE }} --target imageBasicSubsampling