name: CI test

on:
  push:
    branches: [ GHActionSharing ]
  pull_request:
    branches: [ GHActionSharing ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macOS-latest, windows-latest]
        build_type: [Release]
        python-version: ["3.9"]
        config-name: ["default"]

    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Setup OS" 
        uses: ./.github/actions/setup-os
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

      - name: "Get PR config"
        id: "config"
        uses: ./.github/actions/dgtal-config
        with:
          os: ${{ matrix.os }}
          config-name: ${{ matrix.config-name }}

      - name: "Building and Testing"
        uses: ./.github/actions/cmake
        with:
          os: ${{ matrix.os }}
          build-type: ${{ matrix.build_type }}
          build-config: ${{ steps.config.outputs.cmake-config }}
          test: true
