name: CI test

on:
  push:
    branches: [ GHActionSharing ]
  pull_request:
    branches: [ GHActionSharing ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        build_type: [Release]
        python-version: ["3.9"]
        config: ["default"]

    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Setup OS" 
        uses: ./.github/actions/setup-os
        with:
          os: ${{ matrix.os }}
          python: ${{ matrix.python-version }}